site_name: Morgan Willow Chen's Blog
site_description: This is the blog of Morgan Willow Chen.
site_url: https://cmw15004431816.github.io/
nav:
  - Home:
      - index.md
  - Learning record:
    - learning-record/markdown.md
  - Page 1(testing):
      - section/1.md
      - "2": 2.md
  - Page 2(testing):
      - section/2.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  language: en
  features:
    # - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    # - header.autohide
extra:
  alternate:
    - name: English
      lang: en
    - name: 正體中文
      link: /zh-TW/
      lang: zh-TW
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cmw15004431816
      name: Morgan Willow Chen on GitHub
    - icon: fontawesome/brands/telegram
      link: https://t.me/mwc15004431816
      name: Morgan Willow Chen on Telegram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/morgan-willow-chen-5b2337280/
      name: Morgan Willow Chen on LinkedIn
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mwc15004431816
      name: Morgan Willow Chen on Instagram
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=100085061186301
      name: Morgan Willow Chen on Facebook
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@mwc15004431816
      name: Morgan Willow Chen on Threads
copyright: >-
  Copyright &copy; 2024 - 2024 Morgan Willow Chen. All rights reserved.
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
plugins:
  - search
  - social
