site_name: Morgan Willow Chen's Blog (under construction)
site_description: This is the blog of Morgan Willow Chen.
site_url: https://cmw15004431816.link/
nav:
  - Home:
      - index.md
  - Learning record:
      - learning-record/Basic-writing-and-formatting-syntax.md
  - Useful tips:
      - "This is a useful tip on using VIVADO 2024.1": useful-tips/VIVADO.md
      - "This is a useful tip on garbled compressed file names": useful-tips/Compressed-file-name-is-garbled.md
  - Page 1(testing):
      - section/1.md
      - "2": 2.md
  - Page 2(testing):
      - section/2.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: slate)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  language: en
  features:
    # - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    # - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    # - header.autohide
extra:
  alternate:
    - name: English
      lang: en
    - name: 正體中文
      link: /zh-TW/
      lang: zh-TW
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cmw15004431816
      name: Morgan Willow Chen on GitHub
    - icon: fontawesome/brands/stack-overflow
      link: https://stackoverflow.com/users/25033865/morgan-willow-chen
      name: Morgan Willow Chen on Stackoverflow
    - icon: simple/codeforces
      link: https://codeforces.com/profile/cmw15004431816
      name: Morgan Willow Chen on Codeforces
    - icon: fontawesome/brands/telegram
      link: https://t.me/mwc15004431816
      name: Morgan Willow Chen on Telegram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/morgan-willow-chen-5b2337280/
      name: Morgan Willow Chen on LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCrh1YzVHgef6YCR2MJLobEA
      name: Morgan Willow Chen on YouTube
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=100085061186301
      name: Morgan Willow Chen on Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/mwc15004431816
      name: Morgan Willow Chen on Instagram
    - icon: fontawesome/brands/threads
      link: https://www.threads.net/@mwc15004431816
      name: Morgan Willow Chen on Threads
    - icon: fontawesome/brands/quora
      link: https://www.quora.com/profile/Morgan-Willow-Chen-G
      name: Morgan Willow Chen on Quora
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/user/CMW15004431816/
      name: Morgan Willow Chen on Reddit
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.com/cmw15004431816/
      name: Morgan Willow Chen on Pinterest
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@cmw15004431816
      name: Morgan Willow Chen on TikTok
    - icon: fontawesome/brands/spotify
      link: https://open.spotify.com/user/31e225rqd5nznnsnl6bqpjidgyva
      name: Morgan Willow Chen on Spotify
    - icon: fontawesome/brands/tumblr
      link: https://www.tumblr.com/blog/mwc15004431816
      name: Morgan Willow Chen on Tumblr
    - icon: fontawesome/brands/snapchat
      link: https://www.snapchat.com/add/mwc15004431816/
      name: Morgan Willow Chen on Snapchat
copyright: >-
  Copyright &copy; 2024 - 2025 Morgan Willow Chen. All rights reserved. <br><p>Licensed under the <a href="https://github.com/cmw15004431816/cmw15004431816.github.io/blob/main/LICENSE">GPL v3.0 License</a> and <a href="https://github.com/cmw15004431816/cmw15004431816.github.io/blob/main/ADDITIONAL%20TERMS">additional terms</a>.</p>
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - codehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.smartsymbols
  - footnotes
  # - pymdownx.tabbed # You have configured the button to switch between light and dark mode, if you use this extension, you will be unable to switch the mode by clicking the button on the pages that use this extension, other pages will not be affected.
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
plugins:
  - search
  - social
  - mermaid2:
      arguments:
        theme: default
      javascript: https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.8.4/mermaid.min.js
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.1.2/es5/tex-mml-chtml.js
